plugins {
    id("com.gradleup.shadow")
    id("dev.architectury.loom")
    id("architectury-plugin")
    id("matthiesen.shadow-platform-conventions")
}

val generatedResources: File = project(":common").file("src/generated")

architectury {
    platformSetupLoomIde()
    fabric {
        fabricApi {
            configureDataGeneration {
                client = true
                modId = rootProject.property("mod_id") as String
                outputDirectory = generatedResources
            }
        }
    }
}

val shadowBundle: Configuration by configurations.creating

dependencies {
    minecraft(libs.minecraft)
    mappings(loom.officialMojangMappings())
    modImplementation(libs.bundles.fabricModImplementation)
    modImplementation(libs.bundles.fabricModImplementationNoTransitive) { isTransitive = false }
    modCompileOnly(libs.bundles.fabricCompileOnly)
    modRuntimeOnly(libs.bundles.fabricRuntimeOnly)

    implementation(project(":common", configuration = "namedElements"))
    "developmentFabric"(project(":common", configuration = "namedElements"))
    shadowBundle(project(":common", configuration = "transformProductionFabric"))

    testImplementation(libs.junit.api)
    testRuntimeOnly(libs.junit.engine)
}

tasks {
    val cleanupGenerated by registering(Delete::class) {
        description = "Cleans up the generated resources from the common module before copying them to the fabric module."
        delete(file("src/generated"))
    }

    val copyGenerated by registering(Copy::class) {
        description = "Copies the generated resources from the common module to the fabric module, excluding the .cache directory."
        dependsOn(cleanupGenerated)
        mustRunAfter(cleanupGenerated)
        from(project(":common").file("src/generated")) {
            exclude(".cache/")
        }
        into(file("src/generated"))
    }

    processResources {
        dependsOn(copyGenerated)
        filesMatching("fabric.mod.json") {
            expand(project.properties)
        }
        exclude {
            it.file.absolutePath.contains(".cache")
        }
    }

    shadowJar {
        configurations = listOf(shadowBundle)
    }
}
