org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

archives_base_name=custom-gateways
mod_id=custom_gateways
mod_version=1.x-DEV-SNAPSHOT
maven_group=dev.matthiesen
mod_name=Custom Gateways
mod_description=Custom gateways that allow you to create portals to go just about anywhere!
mod_license=MIT License
mod_license_url=https://github.com/Matthiesen-dev/custom-gateways/blob/main/LICENSE
mod_author=Adam Matthiesen
mod_author_id=adammatthiesen
mod_author_url=https://github.com/Adammatthiesen
github_url=https://github.com/Matthiesen-dev/custom-gateways
git_url=github.com/Matthiesen-dev/custom-gateways
modrinth_url=https://modrinth.com/mod/custom-gateways

# Used for prism deployment, not consumed by build-logic
minecraft_version=1.21.1